export const themeOptions = [
  "Figuras de linguagem",
  "Gramatica",
  "Interpretacao",
  "Ortografia",
];

export const defaultCards = [
  {
    id: "fig-1",
    theme: "Figuras de linguagem",
    label: "Figuras de som",
    front: "Paronomasia",
    back: "Figura que aproxima palavras de sons parecidos, mas significados diferentes. Exemplo: 'Conhecer para compreender, compreender para crescer.'",
    hint: "Repare no som semelhante entre as palavras.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "fig-2",
    theme: "Figuras de linguagem",
    label: "Figuras de pensamento",
    front: "Ironia",
    back: "Consiste em dizer o contrario do que se quer comunicar, gerando efeito critico ou humoristico.",
    hint: "O contexto revela o sentido real.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 2, hardCount: 0, mediumCount: 1, easyCount: 1, nextDueAt: Date.now() },
  },
  {
    id: "gram-1",
    theme: "Gramatica",
    label: "Analise sintatica",
    front: "Predicado verbal",
    back: "Predicado cujo nucleo e um verbo significativo, indicando acao ou processo praticado ou sofrido pelo sujeito.",
    hint: "O verbo carrega a ideia principal.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "gram-2",
    theme: "Gramatica",
    label: "Classes de palavras",
    front: "Pronome relativo",
    back: "Pronome que retoma um termo anterior e inicia uma oracao subordinada adjetiva, como 'que', 'quem', 'cujo'.",
    hint: "Ele conecta duas ideias e evita repeticao.",
    createdAt: Date.now(),
    studyMeta: { streak: 2, totalReviews: 4, hardCount: 0, mediumCount: 1, easyCount: 3, nextDueAt: Date.now() + 86400000 },
  },
  {
    id: "int-1",
    theme: "Interpretacao",
    label: "Leitura critica",
    front: "Tese do texto",
    back: "Ideia principal defendida pelo autor ao longo do texto. Costuma aparecer na introducao ou ser retomada na conclusao.",
    hint: "Pergunte: qual ponto o autor quer sustentar?",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "int-2",
    theme: "Interpretacao",
    label: "Leitura inferencial",
    front: "Inferencia",
    back: "Conclusao construida pelo leitor a partir de pistas do texto, mesmo que a informacao nao esteja escrita de forma direta.",
    hint: "Ler nas entrelinhas.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 2, hardCount: 1, mediumCount: 1, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "orto-1",
    theme: "Ortografia",
    label: "Uso das letras",
    front: "Mal ou mau?",
    back: "'Mal' e oposto de 'bem'. 'Mau' e oposto de 'bom'. Exemplo: 'Ele passou mal.' / 'Era um mau exemplo.'",
    hint: "Troque por 'bem' ou 'bom' para testar.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "orto-2",
    theme: "Ortografia",
    label: "Acentuacao",
    front: "Hiato",
    back: "Encontro de duas vogais em silabas separadas, como em 'sa-ida'. Em alguns casos, isso influencia a acentuacao.",
    hint: "As vogais ficam juntas na escrita, mas separadas na pronuncia.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 1, hardCount: 0, mediumCount: 1, easyCount: 0, nextDueAt: Date.now() },
  },
];
