export const themeOptions = [
  "Figuras de linguagem",
  "Gramatica",
  "Interpretacao",
  "Ortografia",
];

export const themeLabels = {
  Todos: "Todos",
  "Figuras de linguagem": "Figuras de linguagem",
  Gramatica: "Gramática",
  Interpretacao: "Interpretação",
  Ortografia: "Ortografia",
};

export function getThemeLabel(theme) {
  return themeLabels[theme] ?? theme;
}

export const defaultCards = [
  {
    id: "fig-1",
    theme: "Figuras de linguagem",
    colorId: "amber",
    label: "Figuras de som",
    front: "Paronomásia",
    back: "Figura que aproxima palavras de sons parecidos, mas significados diferentes. Exemplo: 'Conhecer para compreender, compreender para crescer.'",
    hint: "Repare no som semelhante entre as palavras.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "fig-2",
    theme: "Figuras de linguagem",
    colorId: "amber",
    label: "Figuras de pensamento",
    front: "Ironia",
    back: "Consiste em dizer o contrário do que se quer comunicar, gerando efeito crítico ou humorístico.",
    hint: "O contexto revela o sentido real.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 2, hardCount: 0, mediumCount: 1, easyCount: 1, nextDueAt: Date.now() },
  },
  {
    id: "gram-1",
    theme: "Gramatica",
    colorId: "gold",
    label: "Análise sintática",
    front: "Predicado verbal",
    back: "Predicado cujo núcleo é um verbo significativo, indicando ação ou processo praticado ou sofrido pelo sujeito.",
    hint: "O verbo carrega a ideia principal.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "gram-2",
    theme: "Gramatica",
    colorId: "gold",
    label: "Classes de palavras",
    front: "Pronome relativo",
    back: "Pronome que retoma um termo anterior e inicia uma oração subordinada adjetiva, como 'que', 'quem', 'cujo'.",
    hint: "Ele conecta duas ideias e evita repetição.",
    createdAt: Date.now(),
    studyMeta: { streak: 2, totalReviews: 4, hardCount: 0, mediumCount: 1, easyCount: 3, nextDueAt: Date.now() + 86400000 },
  },
  {
    id: "int-1",
    theme: "Interpretacao",
    colorId: "teal",
    label: "Leitura crítica",
    front: "Tese do texto",
    back: "Ideia principal defendida pelo autor ao longo do texto. Costuma aparecer na introdução ou ser retomada na conclusão.",
    hint: "Pergunte: qual ponto o autor quer sustentar?",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "int-2",
    theme: "Interpretacao",
    colorId: "teal",
    label: "Leitura inferencial",
    front: "Inferência",
    back: "Conclusão construída pelo leitor a partir de pistas do texto, mesmo que a informação não esteja escrita de forma direta.",
    hint: "Ler nas entrelinhas.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 2, hardCount: 1, mediumCount: 1, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "orto-1",
    theme: "Ortografia",
    colorId: "olive",
    label: "Uso das letras",
    front: "Mal ou mau?",
    back: "'Mal' é o oposto de 'bem'. 'Mau' é o oposto de 'bom'. Exemplo: 'Ele passou mal.' / 'Era um mau exemplo.'",
    hint: "Troque por 'bem' ou 'bom' para testar.",
    createdAt: Date.now(),
    studyMeta: { streak: 0, totalReviews: 0, hardCount: 0, mediumCount: 0, easyCount: 0, nextDueAt: Date.now() },
  },
  {
    id: "orto-2",
    theme: "Ortografia",
    colorId: "olive",
    label: "Acentuação",
    front: "Hiato",
    back: "Encontro de duas vogais em sílabas separadas, como em 'sa-ída'. Em alguns casos, isso influencia a acentuação.",
    hint: "As vogais ficam juntas na escrita, mas separadas na pronúncia.",
    createdAt: Date.now(),
    studyMeta: { streak: 1, totalReviews: 1, hardCount: 0, mediumCount: 1, easyCount: 0, nextDueAt: Date.now() },
  },
];
